#!/usr/bin/env python3
"""Historical one-shot: Apple Notes export → content/notes/{folder}/{folder}.notes.md.

Do not re-run on a current vault — import completed 2026; notes are edited directly in git.
Re-running overwrites catalog/import-review.md (wiping manual X attribution entries).

Recovery only, from ingestion/:
  python migrations/import_notes_apple.py -i ../import/apple-notes.txt --dry-run
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

# Run from ingestion/ so parent modules resolve (same as other migrations).
_INGESTION = Path(__file__).resolve().parent.parent
if str(_INGESTION) not in sys.path:
    sys.path.insert(0, str(_INGESTION))

from catalog import catalog_by_number, load_catalog  # noqa: E402
from episode_ids import format_episode_id  # noqa: E402
from markdown_io import read_markdown_body, write_notes_md  # noqa: E402
from paths import IMPORT_REVIEW_PATH, notes_file_path  # noqa: E402

# Episode header: "#200", "200", "ep 200", "#200 Rockefeller", unbulleted title line
EP_HEADER_RE = re.compile(
    r"^(?:#?\s*)?(?:ep(?:isode)?[\s.-]*)?(\d{1,3})\b(?:\s*[-–—:]\s*|\s+|$)",
    re.IGNORECASE,
)
BULLET_RE = re.compile(r"^[\s]*[-•*]\s+")
# Apple Notes may use • prefix; verify.py uses stricter bullet regex for gaps.md
TIMESTAMP_BULLET_RE = re.compile(
    r"^[\s]*[-•*]?\s*(\d{1,2}:\d{2}(?::\d{2})?)\s*[-–—]\s*(.+)$"
)


@dataclass
class NoteBlock:
    episode_number: int | None
    header_line: str
    lines: list[str] = field(default_factory=list)
    bullets: list[str] = field(default_factory=list)


def parse_episode_number_from_line(line: str) -> int | None:
    stripped = line.strip()
    if not stripped or BULLET_RE.match(stripped):
        return None
    m = EP_HEADER_RE.match(stripped)
    if m:
        return int(m.group(1))
    bare = re.fullmatch(r"#?\s*(\d{1,3})\s*", stripped)
    if bare:
        return int(bare.group(1))
    return None


def normalize_bullet(line: str) -> str | None:
    stripped = line.strip()
    if not stripped:
        return None
    m = TIMESTAMP_BULLET_RE.match(stripped)
    if m:
        return f"- {m.group(1)} — {m.group(2).strip()}"
    if BULLET_RE.match(stripped):
        text = BULLET_RE.sub("", stripped).strip()
        if text:
            return f"- {text}"
    return None


def split_blocks(text: str) -> list[NoteBlock]:
    blocks: list[NoteBlock] = []
    current: NoteBlock | None = None

    for raw_line in text.splitlines():
        ep_num = parse_episode_number_from_line(raw_line)
        if ep_num is not None:
            if current is not None:
                blocks.append(current)
            current = NoteBlock(episode_number=ep_num, header_line=raw_line.strip())
            continue
        if current is None:
            continue
        current.lines.append(raw_line)
        bullet = normalize_bullet(raw_line)
        if bullet:
            current.bullets.append(bullet)

    if current is not None:
        blocks.append(current)
    return blocks


def format_notes_body(block: NoteBlock) -> str:
    parts = ["## Raw datapoints", ""]
    if block.bullets:
        parts.extend(block.bullets)
    elif block.lines:
        parts.append("_No timestamp bullets parsed; raw lines preserved below._")
        parts.append("")
        for line in block.lines:
            if line.strip():
                parts.append(f"- {line.strip()}")
    else:
        parts.append("_Empty block._")
    return "\n".join(parts)


def merge_bullets_into_existing(path: Path, bullets: list[str]) -> None:
    """Append new bullets to an existing notes file body."""
    text = path.read_text(encoding="utf-8")
    if text.startswith("---"):
        parts = text.split("---", 2)
        fm_lines = parts[:2]
        body = parts[2] if len(parts) >= 3 else ""
        for bullet in bullets:
            if bullet not in body:
                body = body.rstrip() + "\n" + bullet + "\n"
        path.write_text("---".join(fm_lines) + "---" + body, encoding="utf-8")
    else:
        body = read_markdown_body(path)
        for bullet in bullets:
            if bullet not in body:
                body = body.rstrip() + "\n" + bullet + "\n"
        path.write_text(body, encoding="utf-8")


def update_import_review(
    *,
    written: list[int],
    missing_catalog: list[tuple[int, str]],
    no_bullets: list[tuple[int, str]],
    dry_run: bool,
) -> None:
    lines = [
        "# Import review (manual cleanup)",
        "",
        "Auto-generated by `migrations/import_notes_apple.py`. Fix ambiguous blocks, then re-run.",
        "",
        f"## Last run — wrote {len(written)} notes",
        "",
        "Episode numbers imported: " + (", ".join(str(n) for n in sorted(written)[:50]) or "(none)"),
    ]
    if len(written) > 50:
        lines[-1] += f" … +{len(written) - 50} more"
    lines.append("")

    if missing_catalog:
        lines.append(f"## Unknown episode numbers ({len(missing_catalog)})")
        lines.append("")
        for num, header in missing_catalog:
            lines.append(f"- **#{num}** — `{header}` — not in catalog")
        lines.append("")

    if no_bullets:
        lines.append(f"## Blocks without timestamp bullets ({len(no_bullets)})")
        lines.append("")
        for num, header in no_bullets[:30]:
            lines.append(f"- **#{num}** — `{header}`")
        if len(no_bullets) > 30:
            lines.append(f"- … and {len(no_bullets) - 30} more")
        lines.append("")

    lines.append("## Resolved")
    lines.append("")
    lines.append("_(move fixed items here)_")
    lines.append("")

    if not dry_run:
        IMPORT_REVIEW_PATH.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="[ARCHIVED] Import Apple Notes export into content/notes/"
    )
    parser.add_argument("--input", "-i", required=True, type=Path, help="Path to .txt or .md export")
    parser.add_argument("--dry-run", action="store_true", help="Parse only; do not write files")
    parser.add_argument(
        "--merge",
        action="store_true",
        help="Append new bullets to existing notes (preserves frontmatter)",
    )
    args = parser.parse_args()

    if not args.input.exists():
        raise SystemExit(f"Input not found: {args.input}")

    text = args.input.read_text(encoding="utf-8")
    blocks = split_blocks(text)
    if not blocks:
        raise SystemExit("No episode blocks found. Check export format (episode numbers as headers).")

    rows = load_catalog()
    by_number = catalog_by_number(rows)

    written: list[int] = []
    missing_catalog: list[tuple[int, str]] = []
    no_bullets: list[tuple[int, str]] = []

    for block in blocks:
        if block.episode_number is None:
            continue
        num = block.episode_number
        row = by_number.get(num)
        if not row:
            missing_catalog.append((num, block.header_line))
            continue
        if not block.bullets:
            no_bullets.append((num, block.header_line))

        body = format_notes_body(block)
        if args.dry_run:
            print(f"[dry-run] {format_episode_id(num)}: {len(block.bullets)} bullets")
            written.append(num)
            continue

        out_path = notes_file_path(row["id"], row["slug"], row.get("episode_number"))
        if args.merge and out_path.exists():
            merge_bullets_into_existing(out_path, block.bullets)
        else:
            write_notes_md(row, body, source="apple_notes_import")
        written.append(num)

    update_import_review(
        written=written,
        missing_catalog=missing_catalog,
        no_bullets=no_bullets,
        dry_run=args.dry_run,
    )

    print(f"Parsed {len(blocks)} blocks")
    print(f"Wrote notes for {len(written)} episodes")
    if missing_catalog:
        print(f"Skipped {len(missing_catalog)} unknown episode numbers — see catalog/import-review.md")
    if no_bullets:
        print(f"Warning: {len(no_bullets)} blocks had no timestamp bullets")


if __name__ == "__main__":
    main()
