"""Shared helpers for founders-notes ingestion (re-export shim)."""

from __future__ import annotations

from catalog import (
    catalog_by_id,
    catalog_by_number,
    load_catalog,
    load_jsonl,
    new_row,
    resolve_catalog_row,
    save_catalog,
)
from colossus import (
    colossus_login,
    extract_episode_body,
    extract_episode_description,
    extract_transcript_text,
    is_colossus_transcript_unavailable,
    is_founders_numbered_title,
    load_cookies_file,
    parse_episode_number,
    rate_limit,
    session,
)
from episode_ids import (
    EPISODE_NUMBER_WIDTH,
    format_episode_id,
    legacy_make_id,
    make_id,
    parse_numbered_episode_id,
)
from markdown_io import (
    TIMESTAMP_BULLET_RE,
    has_timestamp_datapoints,
    read_markdown_body,
    utc_now_iso,
    write_frontmatter_md,
    write_notes_md,
    write_post_md,
    write_transcript_md,
)
from paths import (
    CATALOG_PATH,
    CHUNKS_PATH,
    CONTENT_TYPES,
    GAPS_PATH,
    IMPORT_REVIEW_PATH,
    NOTES_DIR,
    POSTS_CORPUS_PATH,
    POSTS_DIR,
    ROOT,
    TRANSCRIPTS_DIR,
    UNMAPPED_POSTS_PATH,
    content_filename,
    episode_content_dir,
    expanded_file_path,
    folder_name,
    notes_dir,
    notes_file_path,
    post_dir,
    post_file_path,
    transcript_dir,
    transcript_filename,
    transcript_path,
)
from sitemap import EPISODE_PATH_RE, SITEMAP_URL, iter_sitemap_episodes

__all__ = [
    "CATALOG_PATH",
    "CHUNKS_PATH",
    "CONTENT_TYPES",
    "EPISODE_NUMBER_WIDTH",
    "GAPS_PATH",
    "IMPORT_REVIEW_PATH",
    "NOTES_DIR",
    "POSTS_CORPUS_PATH",
    "POSTS_DIR",
    "ROOT",
    "SITEMAP_URL",
    "TIMESTAMP_BULLET_RE",
    "TRANSCRIPTS_DIR",
    "UNMAPPED_POSTS_PATH",
    "catalog_by_id",
    "catalog_by_number",
    "colossus_login",
    "content_filename",
    "episode_content_dir",
    "expanded_file_path",
    "extract_episode_body",
    "extract_episode_description",
    "extract_transcript_text",
    "folder_name",
    "format_episode_id",
    "has_timestamp_datapoints",
    "is_colossus_transcript_unavailable",
    "is_founders_numbered_title",
    "iter_sitemap_episodes",
    "legacy_make_id",
    "load_catalog",
    "load_cookies_file",
    "load_jsonl",
    "make_id",
    "new_row",
    "notes_dir",
    "notes_file_path",
    "parse_episode_number",
    "parse_numbered_episode_id",
    "post_dir",
    "post_file_path",
    "rate_limit",
    "read_markdown_body",
    "resolve_catalog_row",
    "save_catalog",
    "session",
    "transcript_dir",
    "transcript_filename",
    "transcript_path",
    "utc_now_iso",
    "write_frontmatter_md",
    "write_notes_md",
    "write_post_md",
    "write_transcript_md",
]
